name: beach_service
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  brasil_fields: ^1.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_mobx: ^1.1.0
  flutter_modular: ^3.1.0
  mobx: ^1.2.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  flutter_modular_test: ^1.0.1
  build_runner: ^1.10.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

## Slidy Scripts
vars:
  get: flutter pub get
  clean: flutter clean
  runner: flutter pub run build_runner
  repair: flutter pub cache repair

scripts:
  mobx_watch: $runner watch
  mobx: $get & $runner watch --delete-conflicting-outputs
  clean: $clean & $get
  socorro: $clean & $repair & $get