name: beach_service
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  brasil_fields: ^1.1.1
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.3
  dio: ^4.0.0
  flutter_mobx: ^1.1.0
  flutter_modular: ^3.1.0
  flutter_svg: ^0.22.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  jwt_decoder: ^2.0.1
  mobx: ^1.2.1+4
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_modular_test: ^1.0.1
  build_runner: ^1.10.12

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_launcher.png
    - assets/images/user-marker.png
    - assets/images/local-marker.png
    - assets/images/empty.svg
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

## Slidy Scripts
vars:
  get: flutter pub get
  clean: flutter clean
  runner: flutter pub run build_runner
  repair: flutter pub cache repair

scripts:
  mobx_watch: $runner watch
  mobx: $get & $runner watch --delete-conflicting-outputs
  clean: $clean & $get
  socorro: $clean & $repair & $get